version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST_NAME=mongo
 